### ISSUE TITLE
npm start dev doesn't create the server

### ISSUE THREAD

**Issue by skyrpex** [cesarandreu/web-app#15]
Hi!

I wanted to try this, so I ran

``` shell
git clone https://github.com/cesarandreu/web-app.git
cd web-app
npm install
npm run dev
```

It compiles fine, but the `http://localhost:8000/` URL doesn't work. Chrome says `ERR_CONNECTION_REFUSED`.

The strange part is that there's no errors...

``` shell
npm run dev

> web-app@1.0.0 dev /home/cpallares/Sandbox/web-app
> webpack-dev-server --history-api-fallback --hot --inline --progress

 70% 1/1 build moduleshttp://localhost:8080/
webpack result is served from http://localhost:8080/
content is served from ./public
404s will fallback to /index.html
...
```

**Comment by cesarandreu** [comment]
Hi @skyrpex! Sorry for the slow reply.
You need to use `http://localhost:8080/`. The port is **8080**, not **8000**.

Please re-open the issue if it doesn't work!
